// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMqVLdPaxzv_apF6Nzjk1p33vREou6Dd4',
    appId: '1:158432568297:web:5976c803d5e309cd5b2178',
    messagingSenderId: '158432568297',
    projectId: 'flutterfirebasefood',
    authDomain: 'flutterfirebasefood.firebaseapp.com',
    storageBucket: 'flutterfirebasefood.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMAWQCWgj2-Oupy4sVxdmK4_QBPMJT9j8',
    appId: '1:158432568297:android:185424ff64a3aaa55b2178',
    messagingSenderId: '158432568297',
    projectId: 'flutterfirebasefood',
    storageBucket: 'flutterfirebasefood.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2bzLa5zupEUCKVto9fIVYzCF498NOQyU',
    appId: '1:158432568297:ios:4601f1687ad3bbef5b2178',
    messagingSenderId: '158432568297',
    projectId: 'flutterfirebasefood',
    storageBucket: 'flutterfirebasefood.firebasestorage.app',
    iosBundleId: 'com.example.foodOrdering',
  );
}
